agents:
  queue: 'macos'

steps:
  - label:
    block: 'Trigger full build'
    key: 'trigger-full-build'

  - label: 'Upload the full test pipeline'
    depends_on: 'trigger-full-build'
    command: buildkite-agent pipeline upload .buildkite/pipeline.full.yml
    timeout_in_minutes: 5
