steps:

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-r21.apk"
      - "build/fixture_r21_url.txt"
      - "build/fixture-r21/*"
    commands:
      - bundle install
      - make fixture-r21
      - bundle exec upload-app --app=./build/fixture-r21.apk --app-id-file=build/fixture_r21_url.txt

  #
  # BitBar PoC
  #
  - label: ':android: BitBar Poc - Android 10 - batch 1'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_10"
          - "--no-tunnel"
          - "--aws-public-ip"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 2
    concurrency_group: 'bitbar-android-10'
    concurrency_method: eager

  - label: ':android: BitBar Poc - Android 10 - batch 2'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture-r21.apk"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-bitbar
        run: android-maze-runner-bitbar
        service-ports: true
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=build/fixture-r21.apk"
          - "--farm=bb"
          - "--device=ANDROID_10"
          - "--no-tunnel"
          - "--aws-public-ip"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 2
    concurrency_group: 'bitbar-android-10'
    concurrency_method: eager
