steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    command: ./scripts/audit-dependency-licenses.sh

  - label: ':android: Build fixture APK r16'
    key: "fixture-r16"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r19'
    key: "fixture-r19"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture_r19_url.txt"
      - "build/fixture-r19/*"
    commands:
      - bundle install
      - make fixture-r19
      - bundle exec upload-app --app=./build/fixture-r19.apk --app-id-file=build/fixture_r19_url.txt

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-r21.apk"
      - "build/fixture_r21_url.txt"
      - "build/fixture-r21/*"
    commands:
      - bundle install
      - make fixture-r21
      - bundle exec upload-app --app=./build/fixture-r21.apk --app-id-file=build/fixture_r21_url.txt

  - label: ':android: Coding standards checks'
    timeout_in_minutes: 20
    agents:
      queue: macos-12-arm
    command: './gradlew --continue checkstyle detekt lint ktlintCheck'

  - label: ':android: CppCheck'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: 'bash ./scripts/run-cpp-check.sh'

  - label: ':android: ClangFormat'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: 'bash ./scripts/run-clang-format-ci-check.sh'

  - label: ':android: Lint mazerunner scenarios'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - cd features/fixtures/mazerunner
      - ./gradlew ktlintCheck detekt checkstyle

  - label: ':android: Android size reporting'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: scripts/run-sizer.sh

  - label: ':android: JVM tests'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: './gradlew test'

  - label: 'Conditionally include device farms/full tests'
    agents:
      queue: macos-12-arm
    command: sh -c .buildkite/pipeline_trigger.sh
