steps:
  - label: ':docker: Build Android base image'
    key: "android-common"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-common
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
      - docker-compose#v3.7.0:
          push:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest

  - label: ':docker: Build Android base CI image (using NDK r16b)'
    key: "android-ci"
    depends_on: "android-common"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}

  - label: ':docker: Build Android maze runner image'
    key: "maze-runner"
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.7.0:
          build: android-maze-runner

  - label: ':docker: Build Android JVM test image'
    key: "android-jvm"
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          build: android-jvm
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-jvm-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push:
            - android-jvm:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-jvm-${BRANCH_NAME}

  - label: ':android: Build fixture APK'
    key: "fixture-apk"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/fixture.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      MINIMAL_FIXTURE: false

  - label: ':android: Build minimal fixture APK'
    key: "minimal-fixture-apk"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/minimal-fixture.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      MINIMAL_FIXTURE: true

  - label: ':android: Android size reporting'
    depends_on: "android-ci"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-sizer

  - label: ':android: Lint'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-jvm
    command: './gradlew lint'

  - label: ':android: Checkstyle'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-jvm
    command: './gradlew checkstyle'

  - label: ':android: Detekt'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-jvm
    command: './gradlew detekt'

  - label: ':android: Ktlint'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-jvm
    command: './gradlew ktlintCheck'

  - label: ':android: CppCheck'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-jvm
    command: 'bash ./scripts/run-cpp-check.sh'

  - label: ':android: JVM tests'
    depends_on: "android-jvm"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          run: android-jvm
    command: './gradlew test'

  - label: ':android: Android 9 smoke tests'
    key: 'android-9-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK 4.4 Instrumentation tests'
    key: 'NDK-smoke-test'
    depends_on: "android-ci"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4"]'
      NDK_VERSION: r12b
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 4.4 smoke tests'
    key: 'android-4-4-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_4_4"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 5 smoke tests'
    key: 'android-5-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 smoke tests'
    key: 'android-6-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
        - "features/smoke_tests"
        - "--app=/app/build/release/fixture.apk"
        - "--farm=bs"
        - "--device=ANDROID_6_0"
        - "--username=$BROWSER_STACK_USERNAME"
        - "--access-key=$BROWSER_STACK_ACCESS_KEY"
        - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 smoke tests'
    key: 'android-7-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.0 smoke tests'
    key: 'android-8-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 8.1 smoke tests'
    key: 'android-8-1-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 10 smoke tests'
    key: 'android-10-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 11 smoke tests'
    key: 'android-11-smoke'
    depends_on: "fixture-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        args:
            - TESTS_DIR=features/smoke_tests
        command:
          - "features/smoke_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Minimal fixture end-to-end tests'
    depends_on: "minimal-fixture-apk"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.2.0:
        download: "build/release/minimal-fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/release/minimal-fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
          - "features/minimal"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/full_pipeline_trigger.sh