steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    command: ./scripts/audit-dependency-licenses.sh

  - label: ':android: Coding standards checks'
    timeout_in_minutes: 20
    agents:
      queue: macos-12-arm
    command: './gradlew --continue checkstyle detekt lint ktlintCheck'

  - label: ':android: CppCheck'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: 'bash ./scripts/run-cpp-check.sh'

  - label: ':android: ClangFormat'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: 'bash ./scripts/run-clang-format-ci-check.sh'

  - label: ':android: Lint mazerunner scenarios'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - cd features/fixtures/mazerunner
      - ./gradlew ktlintCheck detekt checkstyle

  - label: ':android: Android size reporting'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: scripts/run-sizer.sh

  - label: ':android: JVM tests'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: './gradlew test'

  - label: 'Conditionally include device farms/full tests'
    agents:
      queue: macos-12-arm
    command: sh -c .buildkite/pipeline_trigger.sh
