steps:

  - label: ':android: Build fixture APK r16'
    key: "fixture-r16"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture_r16_url.txt"
      - "build/fixture-r16/*"
    commands:
      - bundle install
      - make fixture-r16
      - bundle exec upload-app --app=./build/fixture-r16.apk --app-id-file=build/fixture_r16_url.txt

  - label: ':android: Build fixture APK r19'
    key: "fixture-r19"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture_r19_url.txt"
      - "build/fixture-r19/*"
    commands:
      - bundle install
      - make fixture-r19
      - bundle exec upload-app --app=./build/fixture-r19.apk --app-id-file=build/fixture_r19_url.txt

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - "build/fixture-r21.apk"
      - "build/fixture_r21_url.txt"
      - "build/fixture-r21/*"
    commands:
      - bundle install
      - make fixture-r21
      - bundle exec upload-app --app=./build/fixture-r21.apk --app-id-file=build/fixture_r21_url.txt

  - label: ':android: Android 4.4 NDK r16 smoke tests'
    key: 'android-4-4-smoke'
    depends_on: "fixture-r16"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r16_url.txt"
          - "build/fixture-r16/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner-legacy
        run: android-maze-runner-legacy
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r16_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_4_4"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r16"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 6 NDK r16 smoke tests'
    key: 'android-6-smoke'
    depends_on: "fixture-r16"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r16_url.txt"
          - "build/fixture-r16/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r16_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_6_0_GOOGLE_NEXUS_6"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r16"

  - label: ':android: Android 7 NDK r19 smoke tests'
    key: 'android-7-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r19_url.txt"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r19_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"

  - label: ':android: Android 8.1 NDK r19 smoke tests'
    key: 'android-8-1-smoke'
    depends_on: "fixture-r19"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r19_url.txt"
          - "build/fixture-r19/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r19_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r19"

  - label: ':android: Android 10 NDK r21 smoke tests'
    key: 'android-10-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r21_url.txt"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r21_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"

  - label: ':android: Android 11 NDK r21 smoke tests'
    key: 'android-11-smoke'
    depends_on: "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r21_url.txt"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/smoke_tests"
          - "--app=@/app/build/fixture_r21_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"

  # Android 11+ devices have the GWP-ASAN tool enabled which randomly samples native memory
  # to detect misuse (such as use-after-free, buffer overflow). If a failure is detected then
  # the device will raise a SIGABRT mentioning GWP-ASAN - this can be investigated further
  # by inspecting the devices logs.
  - label: ':android: Android 12 NDK r21 end-to-end tests - batch 1'
    depends_on:
      - "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r21_url.txt"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^a-k].*.feature"
          - "--app=@/app/build/fixture_r21_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_12_0"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: Android 12 NDK r21 end-to-end tests - batch 2'
    depends_on:
      - "fixture-r21"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download:
          - "build/fixture_r21_url.txt"
          - "build/fixture-r21/*"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--exclude=features/full_tests/[^l-z].*.feature"
          - "--app=@/app/build/fixture_r21_url.txt"
          - "--farm=bs"
          - "--device=ANDROID_12_0"
          - "--appium-version=1.20.2"
          - "--fail-fast"
    env:
      TEST_FIXTURE_SYMBOL_DIR: "build/fixture-r21"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
