steps:
  - label: ':android: Android 9 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-9-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK 7.1 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
      NDK_VERSION: r12b
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 12b SDK 9.0 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
      NDK_VERSION: r12b
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK 4.4 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4"]'
      NDK_VERSION: r16b
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK 7.1 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
      NDK_VERSION: r16b
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 16b SDK 9.0 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
      NDK_VERSION: r16b
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK 4.4 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Nexus 5-4.4"]'
      NDK_VERSION: r19
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK 7.1 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel-7.1"]'
      NDK_VERSION: r19
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 19 SDK 9.0 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 3-9.0"]'
      NDK_VERSION: r19
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 21d SDK 10.0 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 4-10.0"]'
      NDK_VERSION: r21d
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: NDK 21d SDK 11.0 Instrumentation tests'
    depends_on:
      - "android-ci"
      - "NDK-smoke-test"
    timeout_in_minutes: 30
    command: ./scripts/build-instrumentation-tests.sh && ./scripts/run-instrumentation-test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: android-ci
    env:
      INSTRUMENTATION_DEVICES: '["Google Pixel 4-11.0"]'
      NDK_VERSION: r21d
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 4.4 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-4-4-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_4_4"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 5 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-5-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_5_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 6 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-6-smoke"
    timeout_in_minutes: 90
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_6_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-7-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8.0 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-8-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 8.1 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-8-1-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_8_1"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    soft_fail:
      - exit_status: "*"

  - label: ':android: Android 10 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-10-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_10_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 11 end-to-end tests'
    depends_on:
      - "fixture-apk"
      - "android-11-smoke"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_11_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: ':android: Minimal fixture end-to-end tests'
    depends_on: "minimal-fixture-apk"
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.2.0:
        download: "build/release/minimal-fixture.apk"
      docker-compose#v3.7.0:
        run: android-maze-runner
        command:
          - "--app=/app/build/release/minimal-fixture.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
          - "--fail-fast"
          - "features/minimal"
    concurrency: 9
    concurrency_group: 'browserstack-app'
