name: instrumentation_tests

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.parallel=true"

jobs:
  android:
    runs-on: macos-latest

    strategy:
      fail-fast: true
      matrix:
        api-level:
          - 29

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck -x :bugsnag-benchmarks:connectedCheck
        env:
          API_LEVEL: ${{ matrix.api-level }}
